---
site_name: MegaLinter by OX Security
site_url: https://megalinter.io
repo_url: https://github.com/oxsecurity/megalinter
edit_uri: tree/main/docs
site_author: Nicolas Vuillamy
# site_description-start
site_description: MegaLinter is an Open-Source tool for CI/CD workflows that analyzes the consistency of your code, IAC, configuration, and scripts in your repository sources, to ensure all your projects sources are clean and formatted whatever IDE/toolbox is used by their developers, powered by OX Security.Supporting 61 languages, 24 formats, 21 tooling formats and ready to use out of the box, as a GitHub action or any CI system highly configurable and free for all uses.Switch to MegaLinter v7 !
# site_description-end
copyright: Copyright &copy; 2024 <a href="https://www.ox.security/?ref=megalinter" target= "_blank">OX Security</a> &amp; <a href="https://github.com/nvuillam" target="_blank">Nicolas Vuillamy</a>
theme:
  name: material
  font: 
    text: Satoshi, sans-serif
  custom_dir: docs/overrides
  features:
    - content.code.copy
    - navigation.instant
    - navigation.footer
  logo: assets/images/mega-linter-square.png
  favicon: assets/images/mega-linter-square.png
  palette:
    primary: white
plugins:
  - glightbox
  - search
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
      restrict_base_path: false
  - mdx_truly_sane_lists
  - attr_list
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js
  - javascripts/gtag.js
  - javascripts/version-mike.js
  - javascripts/quickfixes.js
extra_css:
  - stylesheets/extra.css
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/ox-security/
    - icon: fontawesome/regular/circle-question
      link: https://github.com/oxsecurity/megalinter/issues
      title: Need help ? Post an issue :)
    - icon: fontawesome/brands/github
      link: https://github.com/oxsecurity/megalinter
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/oxsecurity/megalinter
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/NicolasVuillamy
  generator: false
nav:
  - "Home": "index.md"
  - "Quick Start": "quick-start.md"
  - "Installation": 
    - "Assisted Installation": "install-assisted.md"
    - "Which version to use ?": "install-version.md"
    - "GitHub Actions": "install-github.md"
    - "Gitlab CI": "install-gitlab.md"
    - "Azure Pipelines": "install-azure.md"
    - "Bitbucket Pipelines": "install-bitbucket.md"
    - "Jenkins": "install-jenkins.md"
    - "Concourse CI": "install-concourse.md"
    - "Drone CI": "install-drone.md"
    - "Docker (CLI)": "install-docker.md"
    - "Run locally": "install-locally.md"
  - "Configuration": 
    - ".mega-linter.yml file": "config-file.md"
    - "Common Variables": "config-variables.md"
    - "Activation / Deactivation": "config-activation.md"
    - "Filtering files": "config-filtering.md"    
    - "Apply fixes": "config-apply-fixes.md"
    - "Linter scopes variables": "config-linters.md"
    - "Pre-commands": "config-precommands.md"
    - "Post-commands": "config-postcommands.md"
    - "ENV variables security": "config-variables-security.md"
    - "CLI lint mode": "config-cli-lint-mode.md"
  - "Linters":
      - "All supported linters": "supported-linters.md"
      - "Languages linters":
          - "All language linters": "./supported-linters/#languages"
          # language-start
          - "BASH":
              - "All BASH linters": "descriptors/bash.md"
              - "bash-exec": "descriptors/bash_bash_exec.md"
              - "shellcheck": "descriptors/bash_shellcheck.md"
              - "shfmt": "descriptors/bash_shfmt.md"
          - "C":
              - "All C linters": "descriptors/c.md"
              - "cpplint": "descriptors/c_cpplint.md"
              - "clang-format": "descriptors/c_clang_format.md"
          - "CLOJURE":
              - "All CLOJURE linters": "descriptors/clojure.md"
              - "clj-kondo": "descriptors/clojure_clj_kondo.md"
              - "cljstyle": "descriptors/clojure_cljstyle.md"
          - "COFFEE":
              - "All COFFEE linters": "descriptors/coffee.md"
              - "coffeelint": "descriptors/coffee_coffeelint.md"
          - "C++ (CPP)":
              - "All C++ (CPP) linters": "descriptors/cpp.md"
              - "cpplint": "descriptors/cpp_cpplint.md"
              - "clang-format": "descriptors/cpp_clang_format.md"
          - "C# (CSHARP)":
              - "All C# (CSHARP) linters": "descriptors/csharp.md"
              - "dotnet-format": "descriptors/csharp_dotnet_format.md"
              - "csharpier": "descriptors/csharp_csharpier.md"
              - "roslynator": "descriptors/csharp_roslynator.md"
          - "DART":
              - "All DART linters": "descriptors/dart.md"
              - "dartanalyzer": "descriptors/dart_dartanalyzer.md"
          - "GO":
              - "All GO linters": "descriptors/go.md"
              - "golangci-lint": "descriptors/go_golangci_lint.md"
              - "revive": "descriptors/go_revive.md"
          - "GROOVY":
              - "All GROOVY linters": "descriptors/groovy.md"
              - "npm-groovy-lint": "descriptors/groovy_npm_groovy_lint.md"
          - "JAVA":
              - "All JAVA linters": "descriptors/java.md"
              - "checkstyle": "descriptors/java_checkstyle.md"
              - "pmd": "descriptors/java_pmd.md"
          - "JAVASCRIPT":
              - "All JAVASCRIPT linters": "descriptors/javascript.md"
              - "eslint": "descriptors/javascript_eslint.md"
              - "standard": "descriptors/javascript_standard.md"
              - "prettier": "descriptors/javascript_prettier.md"
          - "JSX":
              - "All JSX linters": "descriptors/jsx.md"
              - "eslint": "descriptors/jsx_eslint.md"
          - "KOTLIN":
              - "All KOTLIN linters": "descriptors/kotlin.md"
              - "ktlint": "descriptors/kotlin_ktlint.md"
              - "detekt": "descriptors/kotlin_detekt.md"
          - "LUA":
              - "All LUA linters": "descriptors/lua.md"
              - "luacheck": "descriptors/lua_luacheck.md"
          - "MAKEFILE":
              - "All MAKEFILE linters": "descriptors/makefile.md"
              - "checkmake": "descriptors/makefile_checkmake.md"
          - "PERL":
              - "All PERL linters": "descriptors/perl.md"
              - "perlcritic": "descriptors/perl_perlcritic.md"
          - "PHP":
              - "All PHP linters": "descriptors/php.md"
              - "phpcs": "descriptors/php_phpcs.md"
              - "phpstan": "descriptors/php_phpstan.md"
              - "psalm": "descriptors/php_psalm.md"
              - "phplint": "descriptors/php_phplint.md"
              - "php-cs-fixer": "descriptors/php_php_cs_fixer.md"
          - "POWERSHELL":
              - "All POWERSHELL linters": "descriptors/powershell.md"
              - "powershell": "descriptors/powershell_powershell.md"
              - "powershell_formatter": "descriptors/powershell_powershell_formatter.md"
          - "PYTHON":
              - "All PYTHON linters": "descriptors/python.md"
              - "pylint": "descriptors/python_pylint.md"
              - "black": "descriptors/python_black.md"
              - "flake8": "descriptors/python_flake8.md"
              - "isort": "descriptors/python_isort.md"
              - "bandit": "descriptors/python_bandit.md"
              - "mypy": "descriptors/python_mypy.md"
              - "pyright": "descriptors/python_pyright.md"
              - "ruff": "descriptors/python_ruff.md"
          - "R":
              - "All R linters": "descriptors/r.md"
              - "lintr": "descriptors/r_lintr.md"
          - "RAKU":
              - "All RAKU linters": "descriptors/raku.md"
              - "raku": "descriptors/raku_raku.md"
          - "RUBY":
              - "All RUBY linters": "descriptors/ruby.md"
              - "rubocop": "descriptors/ruby_rubocop.md"
          - "RUST":
              - "All RUST linters": "descriptors/rust.md"
              - "clippy": "descriptors/rust_clippy.md"
          - "SALESFORCE":
              - "All SALESFORCE linters": "descriptors/salesforce.md"
              - "sfdx-scanner-apex": "descriptors/salesforce_sfdx_scanner_apex.md"
              - "sfdx-scanner-aura": "descriptors/salesforce_sfdx_scanner_aura.md"
              - "sfdx-scanner-lwc": "descriptors/salesforce_sfdx_scanner_lwc.md"
              - "lightning-flow-scanner": "descriptors/salesforce_lightning_flow_scanner.md"
          - "SCALA":
              - "All SCALA linters": "descriptors/scala.md"
              - "scalafix": "descriptors/scala_scalafix.md"
          - "SQL":
              - "All SQL linters": "descriptors/sql.md"
              - "sql-lint": "descriptors/sql_sql_lint.md"
              - "sqlfluff": "descriptors/sql_sqlfluff.md"
              - "tsqllint": "descriptors/sql_tsqllint.md"
          - "SWIFT":
              - "All SWIFT linters": "descriptors/swift.md"
              - "swiftlint": "descriptors/swift_swiftlint.md"
          - "TSX":
              - "All TSX linters": "descriptors/tsx.md"
              - "eslint": "descriptors/tsx_eslint.md"
          - "TYPESCRIPT":
              - "All TYPESCRIPT linters": "descriptors/typescript.md"
              - "eslint": "descriptors/typescript_eslint.md"
              - "ts-standard": "descriptors/typescript_ts_standard.md"
              - "prettier": "descriptors/typescript_prettier.md"
          - "Visual Basic .NET (VBDOTNET)":
              - "All Visual Basic .NET (VBDOTNET) linters": "descriptors/vbdotnet.md"
              - "dotnet-format": "descriptors/vbdotnet_dotnet_format.md"
# language-end
      - "Formats linters":
          - "All formats linters": "./supported-linters/#formats"
          # format-start
          - "CSS":
              - "All CSS linters": "descriptors/css.md"
              - "stylelint": "descriptors/css_stylelint.md"
              - "scss-lint": "descriptors/css_scss_lint.md"
          - "ENV":
              - "All ENV linters": "descriptors/env.md"
              - "dotenv-linter": "descriptors/env_dotenv_linter.md"
          - "GRAPHQL":
              - "All GRAPHQL linters": "descriptors/graphql.md"
              - "graphql-schema-linter": "descriptors/graphql_graphql_schema_linter.md"
          - "HTML":
              - "All HTML linters": "descriptors/html.md"
              - "djlint": "descriptors/html_djlint.md"
              - "htmlhint": "descriptors/html_htmlhint.md"
          - "JSON":
              - "All JSON linters": "descriptors/json.md"
              - "jsonlint": "descriptors/json_jsonlint.md"
              - "eslint-plugin-jsonc": "descriptors/json_eslint_plugin_jsonc.md"
              - "v8r": "descriptors/json_v8r.md"
              - "prettier": "descriptors/json_prettier.md"
              - "npm-package-json-lint": "descriptors/json_npm_package_json_lint.md"
          - "LATEX":
              - "All LATEX linters": "descriptors/latex.md"
              - "chktex": "descriptors/latex_chktex.md"
          - "MARKDOWN":
              - "All MARKDOWN linters": "descriptors/markdown.md"
              - "markdownlint": "descriptors/markdown_markdownlint.md"
              - "remark-lint": "descriptors/markdown_remark_lint.md"
              - "markdown-link-check": "descriptors/markdown_markdown_link_check.md"
              - "markdown-table-formatter": "descriptors/markdown_markdown_table_formatter.md"
          - "PROTOBUF":
              - "All PROTOBUF linters": "descriptors/protobuf.md"
              - "protolint": "descriptors/protobuf_protolint.md"
          - "RST":
              - "All RST linters": "descriptors/rst.md"
              - "rst-lint": "descriptors/rst_rst_lint.md"
              - "rstcheck": "descriptors/rst_rstcheck.md"
              - "rstfmt": "descriptors/rst_rstfmt.md"
          - "XML":
              - "All XML linters": "descriptors/xml.md"
              - "xmllint": "descriptors/xml_xmllint.md"
          - "YAML":
              - "All YAML linters": "descriptors/yaml.md"
              - "prettier": "descriptors/yaml_prettier.md"
              - "yamllint": "descriptors/yaml_yamllint.md"
              - "v8r": "descriptors/yaml_v8r.md"
# format-end
      - "Tooling Formats linters":
          - "All tooling formats linters": "./supported-linters/#tooling-formats"
          # tooling_format-start
          - "ACTION":
              - "All ACTION linters": "descriptors/action.md"
              - "actionlint": "descriptors/action_actionlint.md"
          - "ANSIBLE":
              - "All ANSIBLE linters": "descriptors/ansible.md"
              - "ansible-lint": "descriptors/ansible_ansible_lint.md"
          - "API":
              - "All API linters": "descriptors/api.md"
              - "spectral": "descriptors/api_spectral.md"
          - "ARM":
              - "All ARM linters": "descriptors/arm.md"
              - "arm-ttk": "descriptors/arm_arm_ttk.md"
          - "BICEP":
              - "All BICEP linters": "descriptors/bicep.md"
              - "bicep_linter": "descriptors/bicep_bicep_linter.md"
          - "CLOUDFORMATION":
              - "All CLOUDFORMATION linters": "descriptors/cloudformation.md"
              - "cfn-lint": "descriptors/cloudformation_cfn_lint.md"
          - "DOCKERFILE":
              - "All DOCKERFILE linters": "descriptors/dockerfile.md"
              - "hadolint": "descriptors/dockerfile_hadolint.md"
          - "EDITORCONFIG":
              - "All EDITORCONFIG linters": "descriptors/editorconfig.md"
              - "editorconfig-checker": "descriptors/editorconfig_editorconfig_checker.md"
          - "GHERKIN":
              - "All GHERKIN linters": "descriptors/gherkin.md"
              - "gherkin-lint": "descriptors/gherkin_gherkin_lint.md"
          - "KUBERNETES":
              - "All KUBERNETES linters": "descriptors/kubernetes.md"
              - "kubeconform": "descriptors/kubernetes_kubeconform.md"
              - "helm": "descriptors/kubernetes_helm.md"
              - "kubescape": "descriptors/kubernetes_kubescape.md"
          - "OPENAPI":
              - "All OPENAPI linters": "descriptors/openapi.md"
              - "spectral": "descriptors/openapi_spectral.md"
          - "PUPPET":
              - "All PUPPET linters": "descriptors/puppet.md"
              - "puppet-lint": "descriptors/puppet_puppet_lint.md"
          - "SNAKEMAKE":
              - "All SNAKEMAKE linters": "descriptors/snakemake.md"
              - "snakemake": "descriptors/snakemake_snakemake.md"
              - "snakefmt": "descriptors/snakemake_snakefmt.md"
          - "TEKTON":
              - "All TEKTON linters": "descriptors/tekton.md"
              - "tekton-lint": "descriptors/tekton_tekton_lint.md"
          - "TERRAFORM":
              - "All TERRAFORM linters": "descriptors/terraform.md"
              - "tflint": "descriptors/terraform_tflint.md"
              - "terrascan": "descriptors/terraform_terrascan.md"
              - "terragrunt": "descriptors/terraform_terragrunt.md"
              - "terraform-fmt": "descriptors/terraform_terraform_fmt.md"
# tooling_format-end
      - "Other checks":
          - "All other linters": "./supported-linters/#other"
          # other-start
          - "COPYPASTE":
              - "All COPYPASTE linters": "descriptors/copypaste.md"
              - "jscpd": "descriptors/copypaste_jscpd.md"
          - "REPOSITORY":
              - "All REPOSITORY linters": "descriptors/repository.md"
              - "checkov": "descriptors/repository_checkov.md"
              - "devskim": "descriptors/repository_devskim.md"
              - "dustilock": "descriptors/repository_dustilock.md"
              - "git_diff": "descriptors/repository_git_diff.md"
              - "gitleaks": "descriptors/repository_gitleaks.md"
              - "grype": "descriptors/repository_grype.md"
              - "kics": "descriptors/repository_kics.md"
              - "ls-lint": "descriptors/repository_ls_lint.md"
              - "secretlint": "descriptors/repository_secretlint.md"
              - "semgrep": "descriptors/repository_semgrep.md"
              - "syft": "descriptors/repository_syft.md"
              - "trivy": "descriptors/repository_trivy.md"
              - "trivy-sbom": "descriptors/repository_trivy_sbom.md"
              - "trufflehog": "descriptors/repository_trufflehog.md"
          - "SPELL":
              - "All SPELL linters": "descriptors/spell.md"
              - "cspell": "descriptors/spell_cspell.md"
              - "proselint": "descriptors/spell_proselint.md"
              - "vale": "descriptors/spell_vale.md"
              - "lychee": "descriptors/spell_lychee.md"
# other-end
  - "Reporters":
      - "All reporters": "reporters.md"
      - "Text files": "reporters/TextReporter.md"
      - "GitHub Pull Request comments": "reporters/GitHubCommentReporter.md"
      - "Gitlab Merge Request comments": "reporters/GitlabCommentReporter.md"
      - "Azure Pull Request comments": "reporters/AzureCommentReporter.md"
      - "Bitbucket Pull Request comments": "reporters/BitbucketCommentReporter.md"
      - "GitHub Status": "reporters/GitHubStatusReporter.md"
      - "SARIF Reporter": "reporters/SarifReporter.md"
      - "Updated sources": "reporters/UpdatedSourcesReporter.md"
      - "E-mail": "reporters/EmailReporter.md"
      - "File.io": "reporters/FileIoReporter.md"
      - "IDE Configuration": "reporters/ConfigReporter.md"
      - "TAP files": "reporters/TapReporter.md"
      - "Console": "reporters/ConsoleReporter.md"
      - "JSON": "reporters/JsonReporter.md"
      - "Markdown Summary": "reporters/MarkdownSummaryReporter.md"
  - "Flavors":
      - "All flavors": "flavors.md"
      # flavors-start
      - "c_cpp": "flavors/c_cpp.md"
      - "ci_light": "flavors/ci_light.md"
      - "cupcake": "flavors/cupcake.md"
      - "documentation": "flavors/documentation.md"
      - "dotnet": "flavors/dotnet.md"
      - "dotnetweb": "flavors/dotnetweb.md"
      - "formatters": "flavors/formatters.md"
      - "go": "flavors/go.md"
      - "java": "flavors/java.md"
      - "javascript": "flavors/javascript.md"
      - "php": "flavors/php.md"
      - "python": "flavors/python.md"
      - "ruby": "flavors/ruby.md"
      - "rust": "flavors/rust.md"
      - "salesforce": "flavors/salesforce.md"
      - "security": "flavors/security.md"
      - "swift": "flavors/swift.md"
      - "terraform": "flavors/terraform.md"
# flavors-end
      - "Flavors statistics": "flavors-stats.md"
  - "Run locally": "mega-linter-runner.md"
  - "They talk about MegaLinter": "articles.md"
  - "They use MegaLinter": "used-by-stats.md"
  - "List of linters": "all_linters.md"
  - "Plugins": "plugins.md"
  - "Special thanks": "special-thanks.md"
  - "Sponsoring": 'sponsor.md'
  - "Badge": "badge.md"
  - "MegaLinter vs Super-Linter": "mega-linter-vs-super-linter.md"
  - "FAQ": "frequently-asked-questions.md"
  - "Contribute":
      - "How-to Contribute": "how-to-contribute.md"
      - "Contributing Guide": "contributing.md"
  - "License":
      - "AGPL V3 License": "license.md"
      - "License explanations": "license-explanations.md"
  - "Changelog": "CHANGELOG.md"
  - "OX Security": "https://ox.security?ref=megalinter"
