descriptor_id: OPENAPI
descriptor_type: tooling_format
descriptor_flavors:
  - all_flavors # Any project can contain OpenAPI / swagger specification
file_extensions:
  - ".yml"
  - ".yaml"
  - ".json"
file_contains_regex:
  - '"openapi":'
  - '"swagger":'
  - "openapi:"
  - "swagger:"
linters:
  # Spectral
  - linter_name: spectral
    linter_url: https://meta.stoplight.io/docs/spectral/README.md
    linter_repo: https://github.com/stoplightio/spectral
    linter_rules_url: https://meta.stoplight.io/docs/spectral/docs/reference/openapi-rules.md
    linter_banner_image_url: https://github.com/stoplightio/spectral/raw/develop/docs/img/spectral-banner.png
    linter_rules_configuration_url: https://meta.stoplight.io/docs/spectral/docs/getting-started/3-rulesets.md
    config_file_name: .openapirc.yml
    cli_config_arg_name: "-r"
    cli_lint_extra_args:
      - "lint"
    cli_help_arg_name: "--help"
    cli_help_extra_args:
      - "lint"
    examples:
      - "spectral lint myfile.yml"
      - "spectral lint -r .openapirc.yml myfile.yml"
    install:
      npm:
        - "@stoplight/spectral-cli"
    ide:
      stoplight:
        - name: Native integration
          url: https://stoplight.io/studio
      vscode:
        - name: vscode-spectral
          url: https://github.com/stoplightio/vscode-spectral
