name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch PR
        uses: peter-evans/slash-command-dispatch@v3
        id: scd
        if: github.event.issue.pull_request
        with:
          token: ${{ secrets.PAT }}
          commands: |
            build
            help
          issue-type: pull-request
          dispatch-type: workflow
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}
            issue-number=${{ github.event.issue.number }}
            actor=${{ github.actor }}
      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.scd.outputs.error-message }}