name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the event payload context
        env:
          EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$EVENT_CONTEXT"
      - uses: actions/github-script@v6
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.rest.pulls.get(request);
              core.setOutput('head_ref', result.data.head.ref);
              core.setOutput('head_repo_full_name', result.data.head.repo.full_name);
              return result.data;
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      - name: Dump the get-pr payload context
        env:
          GETPR_OUTPUTS: ${{ toJson(steps.get-pr.outputs) }}
        run: echo "$GETPR_OUTPUTS"
      - name: Slash Command Dispatch PR
        uses: peter-evans/slash-command-dispatch@v3
        id: scd
        if: success()
        with:
          token: ${{ secrets.PAT }}
          commands: |
            build
            help
          issue-type: pull-request
          dispatch-type: workflow
          static-args: |
            repository=${{ github.repository }}
            comment-id=${{ github.event.comment.id }}
            issue-number=${{ github.event.issue.number }}
            actor=${{ github.actor }}
            checkout-ref=${{ steps.get-pr.outputs.head_ref }}
            checkout-repository=${{ steps.get-pr.outputs.head_repo_full_name }}
      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.scd.outputs.error-message }}