---
name: "Test mega-linter-runner"
on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  build:
    name: Test MegaLinter runner
    # Set the agent to run on
    runs-on: ubuntu-latest
    # Prevent duplicate run from happening when a forked push is committed
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    timeout-minutes: 60
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.0.2
      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: "12"
      - name: Install dependencies
        run: cd mega-linter-runner && npm ci && npm link
      - name: Run tests
        run: cd mega-linter-runner && npm run test
